VERSION="1.0.6"

all: clean doc package libexec website quasi build

clean:
	rm -rf bin documentation libexec source/c web

doc:
	mkdir -p documentation/html
	mkdir -p documentation/mtx
	mkdir -p documentation/txt
	max2html --out documentation/html/quasi source/mtx/*.mtx
	cat source/mtx/*.mtx > documentation/mtx/quasi.mtx.txt
	cp  source/txt/GPLv3.txt documentation/txt

package:
	cd ..; ln -sf quasi quasi-src-${VERSION}; tar -jcf quasi-src-${VERSION}.tar.bz2 quasi-src-${VERSION}/
	mkdir -p web/download/Quasi
	mv ../quasi-src-${VERSION}.tar.bz2 web/download/Quasi
	rm ../quasi-src-${VERSION}

libexec:
	mkdir -p libexec
	gcc -o libexec/quasi source/legacy/main.c

website:
	mkdir -p web/mtx
	max2html --out web/index source/mtx/*.mtx
	cat source/mtx/*.mtx > web/mtx/quasi.mtx.txt
	cp  source/txt/GPLv3.txt web/GPLv3.txt

quasi:
	libexec/quasi -f source source/mtx/*.mtx

build:
	mkdir -p bin
	gcc -g -o bin/quasi source/c/main.c

prep:
	rm -rf bin libexec source/c
